batch_size: 16
height: 96
learning_rate: 0.0005
max_text_length: 38
model_path: Models/LT_Sentence_Recognition/202512071555
train_epochs: 200
train_workers: 20
vocab: " .?ABDGJKLMNPRSTVabdefgijklmnoprstuvyz\u0105\u0117\u012F\u0160\u0161\u016B\u017D\u017E"
width: 1408
